/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as HomepageIndexImport } from './routes/homepage/index'
import { Route as EditorIndexImport } from './routes/editor/index'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const HomepageIndexRoute = HomepageIndexImport.update({
  path: '/homepage/',
  getParentRoute: () => rootRoute,
} as any)

const EditorIndexRoute = EditorIndexImport.update({
  path: '/editor/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/editor/': {
      id: '/editor/'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof EditorIndexImport
      parentRoute: typeof rootRoute
    }
    '/homepage/': {
      id: '/homepage/'
      path: '/homepage'
      fullPath: '/homepage'
      preLoaderRoute: typeof HomepageIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/editor': typeof EditorIndexRoute
  '/homepage': typeof HomepageIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/editor': typeof EditorIndexRoute
  '/homepage': typeof HomepageIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/editor/': typeof EditorIndexRoute
  '/homepage/': typeof HomepageIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/editor' | '/homepage'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/editor' | '/homepage'
  id: '__root__' | '/' | '/editor/' | '/homepage/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EditorIndexRoute: typeof EditorIndexRoute
  HomepageIndexRoute: typeof HomepageIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EditorIndexRoute: EditorIndexRoute,
  HomepageIndexRoute: HomepageIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/editor/",
        "/homepage/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/editor/": {
      "filePath": "editor/index.tsx"
    },
    "/homepage/": {
      "filePath": "homepage/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
